#!/bin/bash

if ( [ -z "$1" ] || [ -z "$2" ] ); then
  echo "USAGE: $0 <taget> <action> [arument1] [argument2] ..."
  exit 1
fi

#--- ENV -----------------------------------------------------------------------
SCRIPT_NAME="LabRunner"
USER="super"
TARGET=$1
ACTION=$2
ARGUME=`echo $@ |awk '{$1=$2=""; print}'`

#--- HEAD ----------------------------------------------------------------------
echo; echo "--- $SCRIPT_NAME ---"; echo;

echo "ACTION: $TARGET    TARGET: $ACTION    ARGUME: $ARGUME"
echo "  USER: $USER"; echo

ssh $USER@$TARGET -n "sudo mkdir -p /opt/runlab"
ssh $USER@$TARGET -n "sudo chown $USER:$USER /opt/runlab"
scp $ACTION $USER@$TARGET:/opt/runlab/
ssh $USER@$TARGET -n "cd /opt/runlab; sudo ./$ACTION $ARGUME"

#--- END -----------------------------------------------------------------------
echo "LabRunner done."; echo
